### ISSUE TITLE
[Bug] Not working anymore

### ISSUE THREAD

**Issue by NyxIsBad** [E-boi/powercord-dateviewer#1]
As of canary version 86884 the plugin stops showing the actual date; Since the css still seems to work (area still defined), I assume this has something to do with discord updating electron?

**Comment by E-boi** [comment]
Oh hi sorry for the late response, I haven't experienced this bug. What do you mean it isn't the actual date? It is showing the wrong date?

**Comment by NyxIsBad** [comment]
No text is rendered, but the box its contained in gets defined. Inside is blank

**Comment by NyxIsBad** [comment]
https://prnt.sc/1656olt
